package com.roelias.kurubind.core;

import java.lang.reflect.Field;
import java.util.List;
/**
 * Metadata about a table/entity.
 */
public interface TableMetadata {

    String getTableName();

    String getSchema();

    Class<?> getEntityClass();

    Field getIdField();

    String getIdColumnName();

    boolean isIdAutoGenerated();

    List<Field> getInsertableFields();

    List<Field> getUpdatableFields();

    List<Field> getAllFields();

    String getColumnName(Field field);

    DialectImplementation getDialect();

}
