package com.roelias.kurubind.annotation;

import java.lang.annotation.*;


/**
 * Marks a field as as the primary key
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@Documented
public @interface Id {
    /**
     * Indicates whether the id is generated by the database
     */
    boolean generated() default false;
}
